function h = savePlotDialog(pos, filename, width, height, callback)
   
   if nargin < 1
      pos = [200 200];
   end
   
   if nargin < 2 || isempty(height)
      height = 400;
   end   
   
   if nargin < 3 || isempty(width)
      width = 600;
   end   
   
   if nargin < 4
      filename = 'Figure';
   end   

   if nargin < 5
      callback = @min;
   end
   
   h = dialog('Position', [pos(1) - 160 pos(2) + 110 320 220]);
   
   uicontrol(h, 'Style', 'text', 'String', 'File type',...
      'HorizontalAlignment', 'left',...
      'FontSize', 12, 'Position', [10 180 150 25]);
   d.typeField = uicontrol(h, 'Style', 'popup', 'String', 'PNG|EPS|TIFF',...
      'HorizontalAlignment', 'left',...
      'FontSize', 12, 'Position', [156 180 110 25]);
   
   uicontrol(h, 'Style', 'text', 'String', 'File name',...
      'HorizontalAlignment', 'left',...
      'FontSize', 12, 'Position', [10 140 150 25]);
   d.filenameField = uicontrol(h, 'Style', 'edit', 'String', filename,...
      'HorizontalAlignment', 'left',...
      'FontSize', 12, 'BackgroundColor', 'w',...
      'Position', [160 143 150 25]);
   
   uicontrol(h, 'Style', 'text', 'String', 'Image width:',...
      'HorizontalAlignment', 'left',...
      'FontSize', 12, 'Position', [10 100 150 25]);  
   d.widthField = uicontrol(h, 'Style', 'edit', 'String', num2str(width),...
      'HorizontalAlignment', 'left',...
      'FontSize', 12, 'BackgroundColor', 'w',...
      'Position', [160 103 50 25]);

   uicontrol(h, 'Style', 'text', 'String', 'Image height:',...
      'HorizontalAlignment', 'left',...
      'FontSize', 12, 'Position', [10 60 150 25]);  
   d.heightField = uicontrol(h, 'Style', 'edit', 'String', num2str(height),...
      'HorizontalAlignment', 'left',...
      'FontSize', 12, 'BackgroundColor', 'w',...
      'Position', [160 63 50 25]);
   
   uicontrol(h, 'Style', 'pushbutton', 'String', 'Save',...
      'HorizontalAlignment', 'left',...
      'FontSize', 12, 'Callback', {callback, d},...
      'Position', [50 10 80 25]);
   uicontrol(h, 'Style', 'pushbutton', 'String', 'Cancel',...
      'HorizontalAlignment', 'left',...
      'FontSize', 12, 'Callback', @cancel,...
      'Position', [140 10 80 25]);   
end

function cancel(src, event)
   delete(get(src, 'Parent'));
end   